apiVersion: v1
kind: Service
metadata:
  name: task-service-svc
  namespace: crm
  labels:
    app: task-service
spec:
  selector:
    app: task-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP