apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: crm
data:
  APP_ENV: "production"
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "crm"
  POSTGRES_SSLMODE: "disable"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  KAFKA_BROKERS: "kafka-svc:9092"
  KAFKA_GROUP_ID: "notification-service"
  KAFKA_TOPICS: "task.created,task.updated,task.deleted"
  MINIO_ENDPOINT: "minio-svc:9000"
  MINIO_BUCKET: "crm-documents"
  MINIO_USE_SSL: "false"
  MINIO_REGION: "us-east-1"
  LOG_LEVEL: "info"