apiVersion: v1
kind: Secret
metadata:
  name: crm-secret
  namespace: crm
type: Opaque
stringData:
  JWT_SECRET: "change-me-in-production-min-32-chars"
  POSTGRES_USER: "crm"
  POSTGRES_PASSWORD: "crm_secret"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"